In [1]:
import torch

In [2]:
print(torch.__version__)

2.1.2+cpu


In [3]:
import numpy as np

In [4]:
lst = [3,4,5,6]
arr=np.array(lst)

In [5]:
arr.dtype

dtype('int32')

In [6]:
#covert numpy tp [ytorch tensors]

In [7]:
tensors = torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6], dtype=torch.int32)

In [8]:
#index similar to numpy
tensors[:2]

tensor([3, 4], dtype=torch.int32)

In [9]:
tensors[1:4]

tensor([4, 5, 6], dtype=torch.int32)

In [10]:
#disadvantage of from_numpy . the array anad tensor uses the same memory function
tensors[3]=100

In [11]:
tensors

tensor([  3,   4,   5, 100], dtype=torch.int32)

In [12]:
arr

array([  3,   4,   5, 100])

In [13]:
torch.ones(2,3,dtype=torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [17]:
np.arange(0,15).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [20]:
a = torch.tensor(np.arange(0,15).reshape(5,3))
a

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]], dtype=torch.int32)

In [21]:
a[:,0:2]

tensor([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10],
        [12, 13]], dtype=torch.int32)

In [14]:
#artinetic operation

In [23]:
a = torch.tensor([3,4,5], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(a+b)

tensor([ 7.,  9., 11.])


In [24]:
torch.add(a,b)

tensor([ 7.,  9., 11.])

In [25]:
c=torch.zeros(3)

In [26]:
torch.add(a,b,out=c)

tensor([ 7.,  9., 11.])

In [27]:
c

tensor([ 7.,  9., 11.])

In [28]:
#some more operations
a = torch.tensor([3,4,5], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)

In [29]:
##tensor[7,9,15]
torch.add(a,b).sum()

tensor(27.)

In [ ]:
#dot products and mult operations

In [31]:
#some more operations
x = torch.tensor([3,4,5], dtype=torch.float)
y = torch.tensor([4,5,6], dtype=torch.float)

In [32]:
x.mul(y)

tensor([12., 20., 30.])

In [33]:
x.dot(y)

tensor(62.)

In [ ]:
###matrix multiplication

In [34]:
x = torch.tensor([[1,4,2], [1,5,5]], dtype=torch.float)
y = torch.tensor([[5,7],[8,6],[9,11]],dtype=torch.float)

In [35]:
torch.matmul(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [36]:
torch.mm(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [37]:
x@y

tensor([[55., 53.],
        [90., 92.]])